export const cn = {
  auth: {
    loginFailedContent: "登录失败",
    loginFailedTitle: "错误",
    loginSuccess: "登录成功",
    loginFailedContentValidation: "请输入正确的信息",
    loginBtn: "登录",
  },
  labels: {
    logout: "登出",
    managementAccounting: "账务项目",
    accountSetting: '账户设置',
    withdrawal: "取款",
    reportManagement: "报表项目",
    summaryReport: "总计报表",
    receivePaymentReport: "收入报表",
    paymentReport: "付款报告",
    manualReport: "手动添加积分报告",
    quotaModifierReport: "配额修改报告",
    chartManagement: "图表管理",
    summaryChart: "总结图",
    systemManagement: "系统管理",
    chanelInformation: "频道信息",
    record: "记录",
    loginRecord: "登录记录",
    report: "接口记录",
    callbackRecord: "订单回调记录",
    wishlist:"收藏夹列表",
    security:"安全",
  
  },
  headerWeb: {
    dashboard: "仪表板",
    accountInformation: "帐户信息",
    language:'语言',
    amount: "数量",
    income: "今日收入",
  },
  headerPage:{
    homePage: "仪表板",
    accountPage:""
  },
  loginRecord: {
    tableLabels: {
      recordNumber: "记录编号",
      memberId: "会员ID",
      account: "帐户",
      ip: "IP",
      country: "国家",
      city: "城市",
      area: "面积",
      telecommunications: "电信",
      token: "Token",
      status: "状态",
      createdAt: "创建时间",
    },
  },
  report: {
    tableLabels: {
      transactionid: "交易号",
      orderid: "订单ID",
      memo: "备忘录",
      paymentTypes: "付款方式",
      account: "帐户",
      existingAmount: "现有金额",
      actualAmount: "实际金额",
      status: "状态",
      creationTime: "创建时间",
      modifiedTime: "修改的时间",
      bank: "银行",
      bankAccount: "银行账户",
    },
    quota: {
      type: "类型",
      amount: "数量",
      balanceBefore: "平衡 前",
      balanceAfter: "平衡 后",
      createdAt: "Created At",
      transactionId: "交易 ID",
      orderId: "订单ID",
    },
    quickSearch: "快速搜索",
    total: "全部的",
    numberOfSuccessOrders: "成功订单数",
    numberOfFailedOrders: "失败订单数",
    numberOfOrders: "订单数量",
    numberOfSuccessPayInOrders: "成功订单付款次数",
    numberOfFailedPayInOrders: "订单支付失败次数",
    amountOfSuccessPayInOrders: "订单支付成功金额",
    numberOfSuccessPayOutOrders: "支付成功订单数",
    numberOfFailedPayOutOrders: "付款失败次数",
    amountOfSuccessPayOutOrders: "成功支付订单金额",
  },
  managementAccounting: {
    withdrawal: {
      applyForWithdrawal: "申请提款",
      bank: "银行",
      amount: "现有金额",
      accountName: "帐户名称",
      account: "帐户",
      withdrawPassword: "提现密码",
      send: "发送",
      modalTitle: "提款确认",
      modalContent: "您确定要发送提款请求吗？",
      modalConfirm: "确认",
      modalCancel: "取消",
      success: "成功",
      error: "错误",
    },
    accountInfo: {
      accountInformation: "帐户信息",
   
    },
    accountSecurity: {
      accountSecurity: "账户安全",
      changeLoginPassword: "更改登录密码",
      changeWithdrawPassword: "更改提现密码",
      oldPassword: "旧密码",
      newPassword: "新密码",
      retypeNewPassword: "重新输入新密码",
      oldWithdrawPassword: "旧提现密码",
      newWithdrawPassword: "新提现密码",
      retypeNewWithdrawPassword: "重新输入新的提现密码",
      send: "发送",
    },
    accountSetting: {
      title: '账户设置'
    }
  },
  admin: {
    userMngt: {
      id: "id",
      username: "用户名",
      createdAt: "创造在",
      updatedAt: "更新在",
      firstName: "名",
      lastName: "姓",
      role: "角色",
      email: "电子邮件",
      avatar: "阿凡达",
      withdrawPassword: "撤回密码",
      twoFactorAuthenticationCode: "2fa code",
      isEnable2FA: "已验证 GA",
      userListTittle: "用户列表",
      selectUserType: "选择用户类型",
      userType: {
        user: "用户",
        admin: "行政",
        merchant: "商人",
        all: "全部",
      },
      errors: {
        requiredFirstName: "请输入名字",
        requiredLastName: "请输入姓氏",
        requiredEmail: "请输入电子邮件",
        requiredUsername: "请输入用户名",
        requiredPassword: "请输入密码",
        requiredPhone: "请输入电话",
        invalidEmail: "无效的电邮",
        invalidPhone: "无效的电话",
      },
      createUser: {
        firstName: "名",
        lastName: "姓",
        username: "用户名",
        email: "电子邮件",
        password: "密码",
        phone: "电话",
        createUser: "创建用户",
      },
    },
  },
};
